name: CI Windows
on:
  push:
    branches: [ "master" ]
  pull_request:
  workflow_dispatch:
jobs:
  build:
    strategy:
      fail-fast: false
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup MSVC environment
        uses: TheMrMilchmann/setup-msvc-dev@v3
        with:
         arch: x86
         sdk: 10.0.20348.0
         
      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v2
        with:
         version: master
         cache: true

      - name: Output libc env variables
        run: zig libc
      
      - name: Build
        run: zig build --release -Dtarget="x86-windows.xp-msvc"

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: patcher
          path: zig-out/bin/*
          
