name: Publish
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  build:
    strategy:
      fail-fast: false
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup MSVC environment
        uses: TheMrMilchmann/setup-msvc-dev@v3
        with:
         arch: x86
         
      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v2
        with:
         version: master
         cache: true
         
      - name: Build
        run: zig build --libc msvc-x86.txt --release -Dtarget="x86-windows.xp-msvc"

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: patcher
          path: zig-out/bin/*

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: zig-out/bin/*
