name: Publish
on:
  workflow_dispatch:
jobs:
  build:
    strategy:
      fail-fast: false
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup MSVC environment
        uses: TheMrMilchmann/setup-msvc-dev@v3
        with:
         arch: x86
         
      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v2
        with:
         version: master
         cache: true
         
      - name: Build
        run: zig build --libc msvc-x86.txt --release -Dtarget="x86-windows.xp-msvc"

      - name: Calculate hash
        id: hash
        run: | 
          $HASH=(Get-FileHash zig-out/bin/*).Hash
          Write-Output $HASH
          Add-Content -Path $env:GITHUB_OUTPUT -Value "hash=$HASH"

      - name: Create Tag
        id: tag
        run: |
          $TAG="v$((Get-Date).ToString("yyyy-MM-dd-HH-mm"))"
          Write-Output $TAG
          Add-Content -Path $env:GITHUB_OUTPUT -Value "tag=$TAG"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git tag -a $TAG -m "Published version $TAG" $env:GITHUB_SHA
          git push origin $TAG
 
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ComanchePatcher-${{github.sha}}
          path: zig-out/bin/*

      - name: Archive for Release
        run: Compress-Archive -Path zig-out/bin/* -DestinationPath ./ComanchePatcher-${{steps.tag.outputs.tag}}.zip

      - name: Get current job url
        id: jobs
        uses: Tiryoh/gha-jobid-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          job_name: build

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body: |
            | File | SHA256 | |
            | ------------- | ------------- | ------------- |
            | patcher.exe | ${{ steps.hash.outputs.hash }} | [Show in build log](${{ steps.jobs.outputs.html_url }}#step:5:54)|
          prerelease: true
          files: ./ComanchePatcher-${{steps.tag.outputs.tag}}.zip
          tag_name: ${{ steps.tag.outputs.tag }}
